name: Continuous Integration
on: [push]
jobs:
  sample:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files changed
        run: env
